import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper.js";
import LoginBtn from "./components/LoginBtn.js";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body>
          <div
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <LoginBtn />
            {children}
          </div>
        </body>
      </SessionWrapper>
    </html>
  );
}
